# **TEST 1**

In [12]:
import pandas as pd
import numpy as np

In [13]:
# 데이터셋 1: 매출 데이터 (sales)
data = {
    '날짜': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03', '2023-01-03'],
    '지점': ['강남점', '홍대점', '강남점', '홍대점', '강남점', '홍대점'],
    '상품': ['아메리카노', '라떼', '라떼', '아메리카노', '아메리카노', '라떼'],
    '수량': [100, 50, 70, 80, 110, 60],
    '단가': ['4,500', '5,000', '5,000', '4,500', '4,500', '5,000'] # 문자열(콤마 포함) 상태
}
sales = pd.DataFrame(data)
sales

           날짜   지점     상품   수량     단가
0  2023-01-01  강남점  아메리카노  100  4,500
1  2023-01-01  홍대점     라떼   50  5,000
2  2023-01-02  강남점     라떼   70  5,000
3  2023-01-02  홍대점  아메리카노   80  4,500
4  2023-01-03  강남점  아메리카노  110  4,500
5  2023-01-03  홍대점     라떼   60  5,000

In [14]:
# 데이터셋 2: 지점 정보 (branch_info)
branch_data = {
    '지점': ['강남점', '홍대점', '성수점'],
    '매니저': ['김철수', '이영희', '박민수'],
    '오픈일': ['2020-01-01', '2021-03-01', '2022-05-01']
}
branch_info = pd.DataFrame(branch_data)
branch_info

    지점  매니저         오픈일
0  강남점  김철수  2020-01-01
1  홍대점  이영희  2021-03-01
2  성수점  박민수  2022-05-01

In [15]:
# Q1. 데이터 전처리 (형변환)
# sales 데이터프레임의 '단가' 컬럼은 현재 콤마(,)가 포함된 문자열(object) 형태입니다.

# 콤마를 제거하고, 정수형(int 또는 int64)으로 변환하여 다시 '단가' 컬럼에 저장하세요.
sales["단가"]=sales["단가"].str.replace(",","")
sales["단가"]=pd.to_numeric(sales["단가"])
sales

           날짜   지점     상품   수량    단가
0  2023-01-01  강남점  아메리카노  100  4500
1  2023-01-01  홍대점     라떼   50  5000
2  2023-01-02  강남점     라떼   70  5000
3  2023-01-02  홍대점  아메리카노   80  4500
4  2023-01-03  강남점  아메리카노  110  4500
5  2023-01-03  홍대점     라떼   60  5000

In [16]:
# Q2. 파생 변수 생성 (연산)sales 데이터프레임에 **'매출액'**이라는 새로운 컬럼을 추가하세요.
# 계산 공식: 수량 * 단가
sales["매출액"]=sales["수량"]*sales["단가"]
sales

           날짜   지점     상품   수량    단가     매출액
0  2023-01-01  강남점  아메리카노  100  4500  450000
1  2023-01-01  홍대점     라떼   50  5000  250000
2  2023-01-02  강남점     라떼   70  5000  350000
3  2023-01-02  홍대점  아메리카노   80  4500  360000
4  2023-01-03  강남점  아메리카노  110  4500  495000
5  2023-01-03  홍대점     라떼   60  5000  300000

In [19]:
# Q3. 데이터 추출 (조건 필터링)
# sales 데이터프레임에서 **'강남점'**에서 판매된 데이터 중, '매출액'이 450,000원 이상인 행(Row)만 추출하여 출력하세요.
sales[(sales["지점"] == "강남점") & (sales["매출액"] >= 450000)]

           날짜   지점     상품   수량    단가     매출액
0  2023-01-01  강남점  아메리카노  100  4500  450000
4  2023-01-03  강남점  아메리카노  110  4500  495000

In [24]:
# Q4. 데이터 요약 (Groupby)
# 지점별로 총 얼마를 팔았는지 알고 싶습니다. sales 데이터를 이용하여 **'지점'**별 '매출액'의 합계를 구하세요. (결과는 Series 혹은 DataFrame 형태 모두 무방합니다)
sales.groupby('지점')[['매출액']].sum()

         매출액
지점
강남점  1295000
홍대점   910000

In [25]:
# Q5. 데이터 병합 (Merge)
# sales 데이터와 branch_info 데이터를 '지점' 컬럼을 기준으로 합치려고 합니다.
merged = pd.merge(sales, branch_info, how='left')
merged
# sales 데이터는 모두 유지되어야 합니다 (Left Join).

# 합친 결과에서 매니저 정보가 잘 들어왔는지 확인하기 위해 병합된 데이터프레임을 출력하세요.

           날짜   지점     상품   수량    단가     매출액  매니저         오픈일
0  2023-01-01  강남점  아메리카노  100  4500  450000  김철수  2020-01-01
1  2023-01-01  홍대점     라떼   50  5000  250000  이영희  2021-03-01
2  2023-01-02  강남점     라떼   70  5000  350000  김철수  2020-01-01
3  2023-01-02  홍대점  아메리카노   80  4500  360000  이영희  2021-03-01
4  2023-01-03  강남점  아메리카노  110  4500  495000  김철수  2020-01-01
5  2023-01-03  홍대점     라떼   60  5000  300000  이영희  2021-03-01