# [실전 코딩 테스트 2]
### 앞서 만든 데이터프레임(merged_df 혹은 sales)을 계속 사용합니다.
### (만약 데이터가 날아갔다면 Test 1의 초기화 코드를 다시 실행해주세요)

In [98]:
import pandas as pd

In [99]:
# 데이터셋 1: 매출 데이터 (sales)
data = {
    '날짜': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03', '2023-01-03'],
    '지점': ['강남점', '홍대점', '강남점', '홍대점', '강남점', '홍대점'],
    '상품': ['아메리카노', '라떼', '라떼', '아메리카노', '아메리카노', '라떼'],
    '수량': [100, 50, 70, 80, 110, 60],
    '단가': ['4,500', '5,000', '5,000', '4,500', '4,500', '5,000'] # 문자열(콤마 포함) 상태
}
sales = pd.DataFrame(data)
sales

           날짜   지점     상품   수량     단가
0  2023-01-01  강남점  아메리카노  100  4,500
1  2023-01-01  홍대점     라떼   50  5,000
2  2023-01-02  강남점     라떼   70  5,000
3  2023-01-02  홍대점  아메리카노   80  4,500
4  2023-01-03  강남점  아메리카노  110  4,500
5  2023-01-03  홍대점     라떼   60  5,000

In [100]:
# 데이터셋 2: 지점 정보 (branch_info)
branch_data = {
    '지점': ['강남점', '홍대점', '성수점'],
    '매니저': ['김철수', '이영희', '박민수'],
    '오픈일': ['2020-01-01', '2021-03-01', '2022-05-01']
}
branch_info = pd.DataFrame(branch_data)
branch_info

    지점  매니저         오픈일
0  강남점  김철수  2020-01-01
1  홍대점  이영희  2021-03-01
2  성수점  박민수  2022-05-01

In [101]:
# Q1. 날짜 데이터 변환 (시계열 처리)
# 현재 문자열(Object)로 되어 있는 '날짜' 컬럼을 판다스의 날짜/시간 타입(datetime)으로 변환하여 저장하세요.
# 그 후, '날짜' 컬럼에서 '월(month)' 정보만 추출하여 '월'이라는 새로운 컬럼을 만드세요. (dt 접근자 사용)
sales.info()
sales["날짜"]=sales["날짜"].str.replace("-","")
sales["날짜"]=pd.to_numeric(sales["날짜"])
sales
sales["날짜"]=pd.to_datetime(sales["날짜"], format='%Y%m%d')
sales["월"]=sales["날짜"].dt.month
sales

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      6 non-null      object
 1   지점      6 non-null      object
 2   상품      6 non-null      object
 3   수량      6 non-null      int64
 4   단가      6 non-null      object
dtypes: int64(1), object(4)
memory usage: 372.0+ bytes

          날짜   지점     상품   수량     단가  월
0 2023-01-01  강남점  아메리카노  100  4,500  1
1 2023-01-01  홍대점     라떼   50  5,000  1
2 2023-01-02  강남점     라떼   70  5,000  1
3 2023-01-02  홍대점  아메리카노   80  4,500  1
4 2023-01-03  강남점  아메리카노  110  4,500  1
5 2023-01-03  홍대점     라떼   60  5,000  1

In [102]:
# Q2. 피벗 테이블 생성 (pivot_table)
# '지점'을 행(index)으로, '상품'을 열(columns)로 설정하고,
# 값(values)에는 '매출액'의 합계(sum)를 보여주는 피벗 테이블을 만드세요.
# (단, 매출이 없는 경우(NaN)는 0으로 채우세요. hint: fill_value 옵션)

In [103]:
# Q3. 데이터 정렬 (Sorting)
# 전체 데이터에서 '매출액'이 가장 높은 순서대로 데이터를 정렬(내림차순)하고,
# 상위 3개의 판매 기록만 출력하세요.
sales["수량"]=pd.to_numeric(sales["수량"])
sales["단가"]=sales["단가"].str.replace(",","")
sales["단가"]=pd.to_numeric(sales["단가"])
sales["매출액"]=sales["수량"]*sales["단가"]
sales.sort_values("매출액", axis=0, ascending=False).head(3)

          날짜   지점     상품   수량    단가  월     매출액
4 2023-01-03  강남점  아메리카노  110  4500  1  495000
0 2023-01-01  강남점  아메리카노  100  4500  1  450000
3 2023-01-02  홍대점  아메리카노   80  4500  1  360000

In [108]:
# Q4. 문자열 필터링 (String Handling)
# '상품' 이름에 '라떼'라는 글자가 포함된 모든 판매 기록을 필터링하여 출력하세요.
# (hint: .str.contains() 메서드 활용)
sales['상품'].str.contains('라떼').head()

0    False
1     True
2     True
3    False
4    False
Name: 상품, dtype: bool