In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

plt.rcParams["axes.unicode_minus"] = False
plt.rc("font", family="Malgun Gothic")

### [종합 실습 1] 상품 판매 데이터 분석
다음은 한 전자상거래 사이트의 상품 판매 데이터입니다. 고객들이 특정 상품을 구매한 기록이 포함되어 있습니다. 데이터를 활용하여 아래의 문제를 해결하세요.

In [2]:
import pandas as pd

# 예시 상품 판매 데이터
sales_data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product': ['Laptop', 'Mouse', 'Laptop', 'Monitor', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Monitor', 'Keyboard'],
    'Quantity': [1, 2, 1, 1, 2, 1, 1, 3, 1, 1],
    'Price': [1200, 25, 1200, 300, 25, 100, 1200, 25, 300, 100],
    'CustomerID': [1001, 1002, 1001, 1003, 1004, 1002, 1001, 1003, 1005, 1002],
    'OrderDate': ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-10', '2024-01-12', '2024-01-15', '2024-01-18', '2024-01-20', '2024-01-22', '2024-01-25']
}
df_sales = pd.DataFrame(sales_data)
df_sales

   OrderID   Product  Quantity  Price  CustomerID   OrderDate
0      101    Laptop         1   1200        1001  2024-01-05
1      102     Mouse         2     25        1002  2024-01-06
2      103    Laptop         1   1200        1001  2024-01-07
3      104   Monitor         1    300        1003  2024-01-10
4      105     Mouse         2     25        1004  2024-01-12
5      106  Keyboard         1    100        1002  2024-01-15
6      107    Laptop         1   1200        1001  2024-01-18
7      108     Mouse         3     25        1003  2024-01-20
8      109   Monitor         1    300        1005  2024-01-22
9      110  Keyboard         1    100        1002  2024-01-25

### 1. 각 고객(`CustomerID`)별로 총 구매 금액을 계산하세요.

In [3]:
df_sales["OrderTotal"]=df_sales["Quantity"] * df_sales["Price"]
df_sales.groupby(["CustomerID"])[["OrderTotal"]].sum()

            OrderTotal
CustomerID
1001              3600
1002               250
1003               375
1004                50
1005               300

### 2. `Laptop`을 구매한 고객들의 평균 구매 금액을 계산하세요.

In [4]:
df_sales[df_sales["Product"]=="Laptop"].groupby(["Product"])[["Price"]].mean()

          Price
Product
Laptop   1200.0

### 3. 가장 많이 판매된 상품(상품 이름과 판매된 총 수량)을 구하세요.

In [5]:
df_sales.groupby(["Product"])[["Quantity"]].max().sort_values("Quantity",ascending=False).head(1)

         Quantity
Product
Mouse           3

### 4. `OrderDate`가 2024년 1월 10일 이후인 주문만 필터링하여 출력하세요.

In [6]:
df_sales[df_sales["OrderDate"]<='2024-01-10']

   OrderID  Product  Quantity  Price  CustomerID   OrderDate  OrderTotal
0      101   Laptop         1   1200        1001  2024-01-05        1200
1      102    Mouse         2     25        1002  2024-01-06          50
2      103   Laptop         1   1200        1001  2024-01-07        1200
3      104  Monitor         1    300        1003  2024-01-10         300

#### 5. `Product`별로 판매량과 총 판매 금액을 계산한 후, 이를 `Price` 기준으로 내림차순으로 정렬하여 출력하세요.
- hint: `groupby()` 결과에 대해 **여러 컬럼의 합계(sum)** 를 동시에 계산할 수 있는 메서드 사용→.agg()

In [7]:
# df_sales.groupby(["Product"])[["Quantity","Price"]].sum().sort_values(by="Price",ascending=False)
df_sales["TotalPrice"]=df_sales["Quantity"] * df_sales["Price"]
df_sales.groupby(["Product"]).agg(
    {"Quantity": "sum", "TotalPrice":"sum"}
    ).sort_values(by="TotalPrice",ascending=False)

          Quantity  TotalPrice
Product
Laptop           3        3600
Monitor          2         600
Keyboard         2         200
Mouse            7         175

### [종합 실습 2] **컨텐츠 선호 데이터 분석**

다음은 사용자가 다양한 컨텐츠를 평가한 **컨텐츠 선호 데이터**입니다. 사용자가 영화, 음악, 책 등을 평가한 데이터를 바탕으로 분석을 수행하세요.

In [8]:
import pandas as pd

# 예시 컨텐츠 선호 데이터
preference_data = {
    'UserID': [1, 2, 3, 1, 5, 6, 3, 2, 3, 5],
    'ContentID': [101, 102, 101, 103, 104, 105, 106, 101, 107, 102],
    'ContentType': ['Movie', 'Music', 'Movie', 'Book', 'Movie', 'Music', 'Book', 'Movie', 'Music', 'Book'],
    'Rating': [5, 3, 4, 2, 5, 4, 3, 4, 5, 2],
    'ReviewDate': ['2024-02-01', '2024-02-02', '2024-02-03', '2024-02-05', '2024-02-07', '2024-02-10', '2024-02-12', '2024-02-14', '2024-02-15', '2024-02-20']
}
df_preference = pd.DataFrame(preference_data)

### 1. 각 컨텐츠 타입(`ContentType`)별로 평균 평점을 계산하세요.

In [9]:
df_preference.groupby(["ContentType"])[["Rating"]].mean()

               Rating
ContentType
Book         2.333333
Movie        4.500000
Music        4.000000

### 2. 가장 높은 평점을 받은 `ContentID`와 해당 평점을 구하세요.

In [10]:
# rating_max=df_preference.groupby(["ContentID"])[["Rating"]].max()
# rating_max.sort_values("Rating",ascending=False)
max_rating_value=df_preference["Rating"].max()
df_preference[df_preference["Rating"]==max_rating_value][["ContentID","Rating"]]

   ContentID  Rating
0        101       5
4        104       5
8        107       5

### 3. `ReviewDate`가 2024년 2월 10일 이후인 리뷰 중에서 `Rating`이 4 이상인 데이터를 필터링하여 출력하세요.

In [11]:
df_preference[(df_preference["ReviewDate"]>="2024-02-10") & (df_preference["Rating"]>=4)]

   UserID  ContentID ContentType  Rating  ReviewDate
5       6        105       Music       4  2024-02-10
7       2        101       Movie       4  2024-02-14
8       3        107       Music       5  2024-02-15

### 4. 각 사용자(`UserID`)가 평가한 컨텐츠 수를 계산하고, 이를 출력하세요.

In [17]:
df_preference.groupby(['UserID'])[["ContentID"]].count()

        ContentID
UserID
1               2
2               2
3               3
5               2
6               1