In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

plt.rcParams["axes.unicode_minus"] = False
plt.rc("font", family="Malgun Gothic")

### 1. DataFrame객체 생성

In [2]:
data={
    "Name" : ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age" : [25, 30, 35, 40, 28],
    "City" : ["New York", "Los Angeles", "Chicago", "Houston", "San Francisco"],
    "Salary" : [70000, 80000, 120000, 90000, 75000]
}
df=pd.DataFrame(data)
df

      Name  Age           City  Salary
0    Alice   25       New York   70000
1      Bob   30    Los Angeles   80000
2  Charlie   35        Chicago  120000
3    David   40        Houston   90000
4      Eve   28  San Francisco   75000

### 2. 열과 행 선택

In [3]:
# - `Name`과 `City` 열을 선택하여 출력하세요.
df[["Name","City"]]

      Name           City
0    Alice       New York
1      Bob    Los Angeles
2  Charlie        Chicago
3    David        Houston
4      Eve  San Francisco

In [4]:
# 나이가 30 이상인 행을 선택하여 출력하세요.
df[df["Age"]>=30]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago  120000
3    David   40      Houston   90000

### 3. 행과 열 추가

In [5]:
# `Country` 열을 추가하고, 모두 'USA'로 설정하세요.
df["Country"]=pd.DataFrame({"Country":["USA"]*len(df)})
df

      Name  Age           City  Salary Country
0    Alice   25       New York   70000     USA
1      Bob   30    Los Angeles   80000     USA
2  Charlie   35        Chicago  120000     USA
3    David   40        Houston   90000     USA
4      Eve   28  San Francisco   75000     USA

In [6]:
# 새로운 행을 추가하세요. (Name: Frank, Age: 33, City: Seattle, Salary: 85000)
exdata={"Name": "Frank", "Age": 33, "City": "Seattle", "Salary": 85000}
add_df=pd.DataFrame([exdata])
add_df
df = pd.concat([df,add_df], axis=0, ignore_index=True)
df

      Name  Age           City  Salary Country
0    Alice   25       New York   70000     USA
1      Bob   30    Los Angeles   80000     USA
2  Charlie   35        Chicago  120000     USA
3    David   40        Houston   90000     USA
4      Eve   28  San Francisco   75000     USA
5    Frank   33        Seattle   85000     NaN

### 4. 데이터 삭제

In [7]:
# `Salary` 열을 삭제하세요.
df.drop(["Salary"], axis=1)

      Name  Age           City Country
0    Alice   25       New York     USA
1      Bob   30    Los Angeles     USA
2  Charlie   35        Chicago     USA
3    David   40        Houston     USA
4      Eve   28  San Francisco     USA
5    Frank   33        Seattle     NaN

In [8]:
# 'David'가 있는 행을 삭제하세요.
df=df.drop(df[df["Name"]=="David"].index)
df

      Name  Age           City  Salary Country
0    Alice   25       New York   70000     USA
1      Bob   30    Los Angeles   80000     USA
2  Charlie   35        Chicago  120000     USA
4      Eve   28  San Francisco   75000     USA
5    Frank   33        Seattle   85000     NaN

### 5. 데이터 수정

In [9]:
# Age가 35 이상인 사람들의 Salary를 5% 증가시키세요.

df.loc[df["Age"]>=35, 'Salary'] = df.loc[df["Age"]>=35, 'Salary'] * 1.05
df

      Name  Age           City  Salary Country
0    Alice   25       New York   70000     USA
1      Bob   30    Los Angeles   80000     USA
2  Charlie   35        Chicago  126000     USA
4      Eve   28  San Francisco   75000     USA
5    Frank   33        Seattle   85000     NaN

In [10]:
# 'Alice'의 City를 'Boston'으로 수정하세요.
df.loc[0,'City']='Boston'
df

      Name  Age           City  Salary Country
0    Alice   25         Boston   70000     USA
1      Bob   30    Los Angeles   80000     USA
2  Charlie   35        Chicago  126000     USA
4      Eve   28  San Francisco   75000     USA
5    Frank   33        Seattle   85000     NaN

### 6. 데이터 타입 변환

In [11]:
# Age와 Salary의 데이터 타입을 float로 변환하세요.
df[["Age","Salary"]]=df[["Age","Salary"]].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      float64
 2   City     5 non-null      object
 3   Salary   5 non-null      float64
 4   Country  4 non-null      object
dtypes: float64(2), object(3)
memory usage: 412.0+ bytes